### ISSUE TITLE
Error: while compiling deploy_lottery.py

### ISSUE THREAD

**Issue by BookmDan** [PatrickAlphaC/smartcontract-lottery#1]
Description
I am receiving an error

Your Environment
using a mac os
vscode

Basic Information
Working on trying to run the deploy_lottery.py. Having an error importing KeeperCompatibleInterface.sol

Steps to Reproduce
Run scripts/deploy_lottery.py

Additional InformationCompilerError: solc returned the following errors:

This is the error I am seeing, once I run the deploy_lottery.py on brownie:

Compiling contracts...
  Solc version: 0.6.12
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

contracts/Lottery.sol:38:1: ParserError: Expected pragma, import directive or contract/interface/library/struct/enum definition.
Solidity (Ethereum)
^------^

**Comment by PatrickAlphaC** [comment]
How are you getting an issue with `KeeperCompatibleInterface`? That file isn't in this project

**Comment by BookmDan** [comment]
Oh okay. Yes you are right. I meant to write AggregatorV3Interface.

**Comment by BookmDan** [comment]
I am still getting the error: 

CompilerError: solc returned the following errors:

contracts/Lottery.sol:38:1: ParserError: Expected pragma, import directive or contract/interface/library/struct/enum definition.
Solidity (Ethereum)

when running brownie run scripts/deploy_lottery.py

**Comment by PatrickAlphaC** [comment]
Can you send me all your code?

1. Lottery.sol
2. Deploy script
3. config
4. directory structure

Please use triple backticks to format the code as well.

**Comment by BookmDan** [comment]
It is working now.
