### ISSUE TITLE
i am getting an openzeppelin import error

### ISSUE THREAD

**Issue by masudrehman** [PatrickAlphaC/smartcontract-lottery#11]
_ParserError: Source "OpenZeppelin/openzeppelin-contracts@3.4.0/contracts/access/Ownable.sol" not found: File not found.
import "@openzeppelin/contracts/access/Ownable.sol";_

used 0.6.12 and 0.8.7 solidity compiler versions, but still getting this error

**Comment by PatrickAlphaC** [comment]
You can either:

1. create a folder called `.vscode` and  a file called `settings.json`. Then put `{"solidity.remappings": [
    "@chainlink/=/Users/patrick/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2",
    "@openzeppelin/=/Users/patrick/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.3.2"
  ]}` in there.

2. Ignore those linting issues.
