### ISSUE TITLE
Winner is still 0x00000..

### ISSUE THREAD

**Issue by nicolasguasca1** [PatrickAlphaC/smartcontract-lottery#16]
I have deployed the contract on Rinkeby but somehow the VRF is not retrieving the random winner. I have cloned the repo and changed the .env file with my credentials to check if I was missing something but the github one also retrieves a 0x00000 winner. Which could be the possible reasons why the chainlink VRF is not retrieving the randomness accurately? Any ideas on how to debug this?

**Comment by nicolasguasca1** [comment]
Hey. I just checked and the random winner is now the address from where I deployed the contract i.e is working properly. I'm assuming here that the contracts throws the 0x00 address (deployer default value?) until the transaction is completely fulfilled.  I would love to have some light in this topic. Thank you.

**Comment by PatrickAlphaC** [comment]
Ahhh... It's just not sleeping long enough. Could you change `time.sleep` to a longer value?

Closing for now, but feel free to follow up.
