### ISSUE TITLE
Does not work with the Kovan Testnet

### ISSUE THREAD

**Issue by Rohansjamadagni** [PatrickAlphaC/smartcontract-lottery#17]
I'm not sure why, I tried to test it on the kovan testnet instead of rinkeby and the `end_lottery` call always fails with `Fail with error 'Below agreed payment'` in the status code.

Here is the [tx](https://kovan.etherscan.io/tx/0x0b1901b905145293582eb4d97fa2d0067767efcf88077a49a1f062afb54b5370)
Here is the [Smart Contract Address](https://kovan.etherscan.io/address/0x5804bbf463206ad196e017f3a476aea810705c71)

Weirdly enough, it works perfectly with Rinkeby

**Comment by PatrickAlphaC** [comment]
It's your `fee` that is set too low :) 

https://kovan.etherscan.io/address/0x5804bbf463206ad196e017f3a476aea810705c71#readContract

In your `brownie-config.yaml` under `kovan` update it to something like:

```
  kovan:
    fee: 100000000000000000
```

**Comment by Rohansjamadagni** [comment]
Ah I see, Works correctly now.  I think it would be better to store in terms of `ether` and convert to wei using `web3.py` Thanks for the help and the course!
