### ISSUE TITLE
lottery testing questions

### ISSUE THREAD

**Issue by xAslan** [PatrickAlphaC/smartcontract-lottery#18]
Thanks for the tutorial, its been great so far. Had a couple questions, suggestions when it comes to the `test_can_pick_winner_correctly` function in test_lottery_unit.py.

I've noticed that you don't actually need to pass the correct `requestId` to the `callBackWithRandomness` function, you can set it to anything. Would best practice usually be to do some sort of check in our internal `fulfillRandomness` function that the `requestId` matches the original `requestId`, or is this handled automatically in the real contracts and just isn't enforced in the mock?

One other thing I've noticed is that if you call `lottery.startLottery()` without the `{"from": account}` it also still works and brownie doesn't complain. Is there some magic in here that knows what account its from somehow? 

If you supply the wrong account, it does seem to recognize that its wrong, such as `lottery.startLottery({"from": get_account(index=1)})` is an error due to the ownable inheritance.

I'm just having trouble figuring out why `lottery.startLottery()` works without the from; how does brownie know what account to use in that case?

Finallly, the `test_can_pick_winner` from `test_lottery_integration` keeps failing at `assert lottery.recentWinner() == account` with `AssertionError: assert '0x0000000000000000000000000000000000000000' == <LocalAccount '0xbDb...`
but I think this is just because the response from the chainlink node is taking too long, because when I check the contract on etherscan a minute or 2 after the test has failed, then recentWinner finally winds up getting updated to an actual address. Is there a better way to wait for response or should I just guess and put in a slightly longer time in the sleep function?

**Comment by PatrickAlphaC** [comment]
> or is this handled automatically in the real contracts and just isn't enforced in the mock?

Yep! That's it! You can check out the contracts in the github to see: https://github.com/smartcontractkit/chainlink

> is that if you call lottery.startLottery() without the {"from": account} it also still works and brownie doesn't complain.

Can you share an example? 

> but I think this is just because the response from the chainlink node is taking too long

You are 100% correct! I've had it on my todo list to update all these examples with them listening for the event to fire from the `fulfillRandomness` being called... I just haven't got around to it yet. Also I wasn't sure if that was better for teaching people, but its def better in practice, so I think that's what I want to teach moving forward. 

Thanks for the feedback here!! Means a lot.

**Comment by owersbrett** [comment]
Thank you for leaving this comment about the chainlink node taking too long! On etherscan I was thinking, "it looks right..." even tried copy pasting and diffing all the relevant files. @PatrickAlphaC this tutorial has been one of the smoothest I've ever gone through - everything tends to work, and when it doesn't (M1 Config issues) Google has my back. I was compelled to search this out though, and it brought me to exploring the github bugs tab, something I think I should do more often when I am working with packages. I tend to go straight to Google, but this has been rather informative. Thanks again!

**Comment by PatrickAlphaC** [comment]
Glad to hear you're learning so much :) 

Closing this issue for now then.

**Comment by ZeroEkkusu** [comment]
[Here's a discussion](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/535) I've started on how to automate waiting for response and getting the randomness @xAslan @owersbrett

**Comment by gYomii** [comment]
Hi so if I have this issue it means that's working fine right??

**Comment by PatrickAlphaC** [comment]
@gYomii what issue?

**Comment by gYomii** [comment]
@PatrickAlphaC no issue, i wanted just a confirmation

**Comment by PatrickAlphaC** [comment]
What works? Sorry I'm not following the conversation.

**Comment by gYomii** [comment]
No issue, all is fine!

**Comment by abdullahkhan70** [comment]
Hello, @PatrickAlphaC I am learning blockchain through your tutorial series. But when I reached the >test_can_pick_winner section where you made an integration test case for the Lottery. Whenever I am trying to run the test through Alchemy's Rinkeby or Kovan they both return the same assert error:

>E       AssertionError: assert '0x0000000000000000000000000000000000000000' == <LocalAccount >'0xC9f3024d428Bf04a5b3f27d335Fc2b74990f3Df0'>
>E        +  where '0x0000000000000000000000000000000000000000' = <ContractCall 'recentWinner()'>()
>E        +    where <ContractCall 'recentWinner()'> = <Lottery Contract >'0x873B28d560893b8D145687706970e8a6e568D56D'>.recentWinner

It always returns this same 0x0000000000000000000000000000000000000000 address whenever it calls this function.

**Comment by PatrickAlphaC** [comment]
You'll likely need to `time.sleep` longer. 

We've updated the [chainlink-mix](https://github.com/smartcontractkit/chainlink-mix) to use a `listen_for_event` function to listen for event if you'd like to add that!

**Comment by sumankwan** [comment]
hi any tutorial for VRF V2 subscription model on the lottery project?

**Comment by PatrickAlphaC** [comment]
Hi @sumankwan! You can check out the contracts from the hardhat course: https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc

This uses VRFv2, but it's written with hardhat tooling. It would be easy enough to add the brownie tooling if you'd like!
