### ISSUE TITLE
Not able to compile code in VS Code

### ISSUE THREAD

**Issue by siddharthalodha** [PatrickAlphaC/smartcontract-lottery#19]
Hi,
I am sorry if this has been asked before. I tried searching but couldn't find any solutions that fix it.

I was able to run all code before smartcontract-lottery. 

Now, I am unable to compile using brownies as I keep on getting Solidiity compiler errors like this. If i try to fix one file, they come in others. I have tried resetting the compiler version using vscode but it seems like it is always using the 0.8.10 version. I tried overriding using the brownie config file, but then i get different version errors. 

ParserError: Source file requires different compiler version (current compiler is 0.8.10+commit.fc410830.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> /Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol:2:1:
  |
2 | pragma solidity ^0.6.0;
  | ^^^^^^^^^^^^^^^^^^^^^^^

ParserError: Source file requires different compiler version (current compiler is 0.8.10+commit.fc410830.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> /Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.6/interfaces/AggregatorInterface.sol:2:1:
  |
2 | pragma solidity ^0.6.0;
  | ^^^^^^^^^^^^^^^^^^^^^^^

ParserError: Source file requires different compiler version (current compiler is 0.8.10+commit.fc410830.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> /Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.6/VRFConsumerBase.sol:2:1:
  |
2 | pragma solidity ^0.6.0;
  | ^^^^^^^^^^^^^^^^^^^^^^^

ParserError: Source file requires different compiler version (current compiler is 0.8.10+commit.fc410830.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> /Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.6/interfaces/LinkTokenInterface.sol:2:1:
  |
2 | pragma solidity ^0.6.0;

**Comment by siddharthalodha** [comment]
I tried setting the default compiler to 0.6.0 but then i get the following error.

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.4/ERC677Token.sol:1:1: ParserError: Source file requires different compiler version (current compiler is 0.6.6+commit.6c089d02.Darwin.appleclang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;

**Comment by siddharthalodha** [comment]
I was able to change the compiler version in all the files but then I am getting these errors.

ompilerError: solc returned the following errors:

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:9:1: TypeError: Contract "ERC20Basic" should be marked as abstract.
contract ERC20Basic {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:11:3: Missing implementation:
  function balanceOf(address who) public view returns (uint256);
  ^------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: Missing implementation:
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:11:1: TypeError: Contract "ERC20" should be marked as abstract.
contract ERC20 is linkERC20Basic {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:12:3: Missing implementation:
  function allowance(address owner, address spender) public view returns (uint256);
  ^-------------------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:14:3: Missing implementation:
  function approve(address spender, uint256 value) public returns (bool);
  ^---------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:11:3: Missing implementation:
  function balanceOf(address who) public view returns (uint256);
  ^------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: Missing implementation:
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:13:3: Missing implementation:
  function transferFrom(address from, address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC677.sol:5:1: TypeError: Contract "ERC677" should be marked as abstract.
contract ERC677 is linkERC20 {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:12:3: Missing implementation:
  function allowance(address owner, address spender) public view returns (uint256);
  ^-------------------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:14:3: Missing implementation:
  function approve(address spender, uint256 value) public returns (bool);
  ^---------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:11:3: Missing implementation:
  function balanceOf(address who) public view returns (uint256);
  ^------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: Missing implementation:
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC677.sol:6:3: Missing implementation:
  function transferAndCall(address to, uint value, bytes memory data) public returns (bool success);
  ^------------------------------------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:13:3: Missing implementation:
  function transferFrom(address from, address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC677Receiver.sol:4:1: TypeError: Contract "ERC677Receiver" should be marked as abstract.
contract ERC677Receiver {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC677Receiver.sol:5:3: Missing implementation:
  function onTokenTransfer(address _sender, uint _value, bytes memory _data) public;
  ^--------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/ERC677Token.sol:16:3: TypeError: Overriding function is missing "override" specifier.
  function transferAndCall(address _to, uint _value, bytes memory _data)
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC677.sol:6:3: Overridden function is here:
  function transferAndCall(address to, uint value, bytes memory data) public returns (bool success);
  ^------------------------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC677.sol:6:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function transferAndCall(address to, uint value, bytes memory data) public returns (bool success);
  ^------------------------------------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/ERC677Token.sol:16:3: Overriding function is here:
  function transferAndCall(address _to, uint _value, bytes memory _data)
  ^ (Relevant source part starts here and spans across multiple lines).

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/ERC677Token.sol:8:1: TypeError: Contract "ERC677Token" should be marked as abstract.
contract ERC677Token is ERC677 {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:12:3: Missing implementation:
  function allowance(address owner, address spender) public view returns (uint256);
  ^-------------------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:14:3: Missing implementation:
  function approve(address spender, uint256 value) public returns (bool);
  ^---------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:11:3: Missing implementation:
  function balanceOf(address who) public view returns (uint256);
  ^------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: Missing implementation:
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:13:3: Missing implementation:
  function transferFrom(address from, address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/BasicToken.sol:22:3: TypeError: Overriding function is missing "override" specifier.
  function transfer(address _to, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: Overridden function is here:
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/BasicToken.sol:22:3: Overriding function is here:
  function transfer(address _to, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/BasicToken.sol:29:3: TypeError: Overriding function is missing "override" specifier.
  function balanceOf(address _owner) public view returns (uint256 balance) {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:11:3: Overridden function is here:
  function balanceOf(address who) public view returns (uint256);
  ^------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:11:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function balanceOf(address who) public view returns (uint256);
  ^------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/BasicToken.sol:29:3: Overriding function is here:
  function balanceOf(address _owner) public view returns (uint256 balance) {
  ^ (Relevant source part starts here and spans across multiple lines).

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:26:3: TypeError: Overriding function is missing "override" specifier.
  function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:13:3: Overridden function is here:
  function transferFrom(address from, address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:13:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function transferFrom(address from, address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:26:3: Overriding function is here:
  function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:44:3: TypeError: Overriding function is missing "override" specifier.
  function approve(address _spender, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:14:3: Overridden function is here:
  function approve(address spender, uint256 value) public returns (bool);
  ^---------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:14:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function approve(address spender, uint256 value) public returns (bool);
  ^---------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:44:3: Overriding function is here:
  function approve(address _spender, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:50:3: TypeError: Overriding function is missing "override" specifier.
  function allowance(address _owner, address _spender) public  view returns (uint256 remaining) {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:12:3: Overridden function is here:
  function allowance(address owner, address spender) public view returns (uint256);
  ^-------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:12:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function allowance(address owner, address spender) public view returns (uint256);
  ^-------------------------------------------------------------------------------^
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:50:3: Overriding function is here:
  function allowance(address _owner, address _spender) public  view returns (uint256 remaining) {
  ^ (Relevant source part starts here and spans across multiple lines).

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:15:1: TypeError: Derived contract must override function "balanceOf". Two or more base classes define function with same name and parameter types.
contract StandardToken is linkERC20, linkBasicToken {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/BasicToken.sol:29:3: Definition in "BasicToken": 
  function balanceOf(address _owner) public view returns (uint256 balance) {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:11:3: Definition in "ERC20Basic": 
  function balanceOf(address who) public view returns (uint256);
  ^------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:15:1: TypeError: Derived contract must override function "transfer". Two or more base classes define function with same name and parameter types.
contract StandardToken is linkERC20, linkBasicToken {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/BasicToken.sol:22:3: Definition in "BasicToken": 
  function transfer(address _to, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: Definition in "ERC20Basic": 
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^

contracts/test/LinkToken.sol:23:5: TypeError: Overriding function is missing "override" specifier.
    function transferAndCall(
    ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/ERC677Token.sol:16:3: Overridden function is here:
  function transferAndCall(address _to, uint _value, bytes memory _data)
  ^ (Relevant source part starts here and spans across multiple lines).

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/ERC677Token.sol:16:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function transferAndCall(address _to, uint _value, bytes memory _data)
  ^ (Relevant source part starts here and spans across multiple lines).
contracts/test/LinkToken.sol:23:5: Overriding function is here:
    function transferAndCall(
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/test/LinkToken.sol:36:5: TypeError: Overriding function is missing "override" specifier.
    function transfer(address _to, uint256 _value)
    ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: Overridden function is here:
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^
contracts/test/LinkToken.sol:36:5: Overriding function is here:
    function transfer(address _to, uint256 _value)
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/test/LinkToken.sol:36:5: TypeError: Overriding function is missing "override" specifier.
    function transfer(address _to, uint256 _value)
    ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: Overridden function is here:
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^
contracts/test/LinkToken.sol:36:5: Overriding function is here:
    function transfer(address _to, uint256 _value)
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/test/LinkToken.sol:49:5: TypeError: Overriding function is missing "override" specifier.
    function approve(address _spender, uint256 _value)
    ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:44:3: Overridden function is here:
  function approve(address _spender, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:44:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function approve(address _spender, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).
contracts/test/LinkToken.sol:49:5: Overriding function is here:
    function approve(address _spender, uint256 _value)
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/test/LinkToken.sol:49:5: TypeError: Overriding function is missing "override" specifier.
    function approve(address _spender, uint256 _value)
    ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:14:3: Overridden function is here:
  function approve(address spender, uint256 value) public returns (bool);
  ^---------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:14:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function approve(address spender, uint256 value) public returns (bool);
  ^---------------------------------------------------------------------^
contracts/test/LinkToken.sol:49:5: Overriding function is here:
    function approve(address _spender, uint256 _value)
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/test/LinkToken.sol:49:5: TypeError: Function needs to specify overridden contracts "ERC20" and "StandardToken".
    function approve(address _spender, uint256 _value)
    ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:15:1: This contract: 
contract StandardToken is linkERC20, linkBasicToken {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:11:1: This contract: 
contract ERC20 is linkERC20Basic {
^ (Relevant source part starts here and spans across multiple lines).

contracts/test/LinkToken.sol:63:5: TypeError: Overriding function is missing "override" specifier.
    function transferFrom(
    ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:26:3: Overridden function is here:
  function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:26:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
  ^ (Relevant source part starts here and spans across multiple lines).
contracts/test/LinkToken.sol:63:5: Overriding function is here:
    function transferFrom(
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/test/LinkToken.sol:63:5: TypeError: Overriding function is missing "override" specifier.
    function transferFrom(
    ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:13:3: Overridden function is here:
  function transferFrom(address from, address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:13:3: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
  function transferFrom(address from, address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------------------------^
contracts/test/LinkToken.sol:63:5: Overriding function is here:
    function transferFrom(
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/test/LinkToken.sol:63:5: TypeError: Function needs to specify overridden contracts "ERC20" and "StandardToken".
    function transferFrom(
    ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:15:1: This contract: 
contract StandardToken is linkERC20, linkBasicToken {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:11:1: This contract: 
contract ERC20 is linkERC20Basic {
^ (Relevant source part starts here and spans across multiple lines).

contracts/test/LinkToken.sol:7:1: TypeError: Derived contract must override function "allowance". Two or more base classes define function with same name and parameter types.
contract LinkToken is linkStandardToken, ERC677Token {
^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/vendor/StandardToken.sol:50:3: Definition in "StandardToken": 
  function allowance(address _owner, address _spender) public  view returns (uint256 remaining) {
  ^ (Relevant source part starts here and spans across multiple lines).
/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:12:3: Definition in "ERC20": 
  function allowance(address owner, address spender) public view returns (uint256);
  ^-------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:11:3: TypeError: Functions without implementation must be marked virtual.
  function balanceOf(address who) public view returns (uint256);
  ^------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20Basic.sol:12:3: TypeError: Functions without implementation must be marked virtual.
  function transfer(address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:12:3: TypeError: Functions without implementation must be marked virtual.
  function allowance(address owner, address spender) public view returns (uint256);
  ^-------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:13:3: TypeError: Functions without implementation must be marked virtual.
  function transferFrom(address from, address to, uint256 value) public returns (bool);
  ^-----------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC20.sol:14:3: TypeError: Functions without implementation must be marked virtual.
  function approve(address spender, uint256 value) public returns (bool);
  ^---------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC677.sol:6:3: TypeError: Functions without implementation must be marked virtual.
  function transferAndCall(address to, uint value, bytes memory data) public returns (bool success);
  ^------------------------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/interfaces/ERC677Receiver.sol:5:3: TypeError: Functions without implementation must be marked virtual.
  function onTokenTransfer(address _sender, uint _value, bytes memory _data) public;
  ^--------------------------------------------------------------------------------^

/Users/silodha/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2/contracts/src/v0.4/ERC677Token.sol:20:5: TypeError: Member "transfer" not found or not visible after argument-dependent lookup in contract super ERC677Token. Use "address(super).transfer" to access this address member.
    super.transfer(_to, _value);

**Comment by PatrickAlphaC** [comment]
Glad you got it!

**Comment by iamhitarth** [comment]
@siddharthalodha how did you end up resolving this version mismatch?
