### ISSUE TITLE
[QUESTION] - Why don't we add the VRF import to the dependencies in brownie-config.yaml?

### ISSUE THREAD

**Issue by Magofoco** [PatrickAlphaC/smartcontract-lottery#2]
I am watching this video.
https://www.youtube.com/watch?v=M576WGiDBdQ

I am in the smart contract lottery part when we have to generate a random number using chainlink VRF.

I imported on top of my .**sol** file this line:
`import "@chainlink/contracts/src/v0.6/VRFConsumerBase.sol";`

My question is, why are we not adding this dependency and this remapping into **brownie-config.yaml** as we did for `import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";` and `import "@openzeppelin/contracts/access/Ownable.sol";` ?

Thanks

**Comment by PatrickAlphaC** [comment]
We do: 

https://github.com/PatrickAlphaC/smartcontract-lottery/blob/main/brownie-config.yaml

When we pull in `@chainlink/contracts` we get to pull in everything from that package. Let me know if that doesn't make sense.
