### ISSUE TITLE
test_lottery.py

### ISSUE THREAD

**Issue by Madgeniusblink** [PatrickAlphaC/smartcontract-lottery#20]
would anyone be able to help me figure out what the issue here is?

I already check my brownie-config.yaml and it looks good

![Screen Shot 2021-12-03 at 8 08 51 PM](https://user-images.githubusercontent.com/42707764/144694786-362ca2b8-5dd6-4ea4-b16e-0b48ff4566d5.png)

**test_lottery.py file**
![Screen Shot 2021-12-03 at 8 09 15 PM](https://user-images.githubusercontent.com/42707764/144694796-9a15549e-294d-471a-baba-8e197817152f.png)

FAIL ERROR
![Screen Shot 2021-12-03 at 8 03 47 PM](https://user-images.githubusercontent.com/42707764/144694646-6b07994b-a087-436e-92f2-60ecdf721ade.png)

**Comment by PatrickAlphaC** [comment]
I'd need the rest of the output.

Could you try using the debugger?

run:

```
brownie test --pdb
```

And then when it drops you into the shell run:

```
lottery.getEntranceFee()
```

and see what it outputs.  Also double check that your smart contract has a variable named exactly `getEntranceFee`

Closing for now, feel free to follow up.
