### ISSUE TITLE
Hello, All, I am getting below "error" while testing my "integration test" but it doesn't show any error during "unit test". Can anybody, Please help!

### ISSUE THREAD

**Issue by sumitdevtech** [PatrickAlphaC/smartcontract-lottery#21]
```
sumitdevtech@sumit-VirtualBox:~/smartcontract-lottery$ brownie test -k test_can_pick_winner --network rinkeby -s
Brownie v1.17.1 - Python development framework for Ethereum

============================ test session starts =============================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /home/sumitdevtech/.local/pipx/venvs/eth-brownie/bin/python
cachedir: .pytest_cache
hypothesis profile 'brownie-verbose' -> verbosity=2, deadline=None, max_examples=50, stateful_step_count=10, report_multiple_bugs=False, database=DirectoryBasedExampleDatabase(PosixPath('/home/sumitdevtech/.brownie/hypothesis'))
rootdir: /home/sumitdevtech/smartcontract-lottery
plugins: eth-brownie-1.17.1, xdist-1.34.0, web3-5.24.0, forked-1.3.0, hypothesis-6.24.0
collected 6 items / 4 deselected / 2 selected                                

tests/test_lottery_integration.py::test_can_pick_winner FAILED
tests/test_lottery_unit.py::test_can_pick_winner_correctly SKIPPED

================================== FAILURES ==================================
____________________________ test_can_pick_winner ____________________________

    def test_can_pick_winner():
        if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
            pytest.skip()
>       lottery = deploy_lottery()

tests/test_lottery_integration.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
scripts/deploy_lottery.py:13: in deploy_lottery
    lottery = Lottery.deploy(
/usr/lib/python3.8/pathlib.py:1236: in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
/usr/lib/python3.8/pathlib.py:1222: in open
    return io.open(self, mode, buffering, encoding, errors, newline,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = PosixPath('/home/sumitdevtech/smartcontract-lottery/contracts/https:/docs.chain.link/docs/get-the-latest-price')
name = '/home/sumitdevtech/smartcontract-lottery/contracts/https:/docs.chain.link/docs/get-the-latest-price'
flags = 524288, mode = 438

    def _opener(self, name, flags, mode=0o666):
        # A stub for the opener argument to built-in open()
>       return self._accessor.open(self, flags, mode)
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/sumitdevtech/smartcontract-lottery/contracts/https:/docs.chain.link/docs/get-the-latest-price'

/usr/lib/python3.8/pathlib.py:1078: FileNotFoundError
========================== short test summary info ===========================
FAILED tests/test_lottery_integration.py::test_can_pick_winner - FileNotFou...
=========== 1 failed, 1 skipped, 4 deselected in 65.86s (0:01:05) ============
```

**Comment by PatrickAlphaC** [comment]
What does your `deploy_lottery` function look like?

**Comment by sumitdevtech** [comment]
def deploy_lottery():
    # pass
    # 1st thing we always need is an account to deploy the contract
    # account = get_account(id="freecodecamp-account")
    # Just for checking if we run "brownie run scripts/deploy_lottery.py" after the above code gets saved then we will found much more liberal get_account()
    account = get_account()
    lottery = Lottery.deploy(
        # Similar to our `contructor()` in "Lottery.sol"
        # Now, The way we did that in "Brownie_FundMe" is that we did it in a way where we checked to see if we were on a local chain or not....?
        # If we're on a local chain then we would just pull our addresses directly from our "brownie-config.yaml" file but if weren't on the local chain then we'd...
        # ...deploy some "mocks" and use the address of those "mocks" we're going to do the same thing here...
        # ...but make our lives a little-bit easier by taking the whole process of "Checking" that we're on the local chain or not...
        # ...& "Mocking" into a single function called "get_contract()" and add this function in "helpful_scripts.py"
        get_contract("eth_usd_price_feed").address,  # address _priceFeedAddress
        get_contract("vrf_coordinator").address,  # address _vrfCoordinator
        get_contract("link_token").address,  # address _link
        config["networks"][network.show_active()]["fee"],  # uint256 _fee
        config["networks"][network.show_active()]["keyhash"],  # bytes32 _keyhash
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify", False),
        # here `.get(verify", False)` says "get" that "verify key" but if there is no "verify key" there just default to "false"
    )
    print("Deployed lottery!")
    return lottery

**Comment by sumitdevtech** [comment]
> What does your `deploy_lottery` function look like?

By the way, Thank you! Patrick for your quick reply and for creating such a great course for free.
I enjoyed and learned a lot till here in the course and I am moving ahead...

**Comment by PatrickAlphaC** [comment]
Glad you're learning.

Please format your code with 3 backticks (```) before and after your code to make it look like it does now in the future. 

What's your lottery look like? There is likely something off with your code not looking the same as the sample code. How about your `brownie-config.yaml`? Or any other information you have.

**Comment by sumitdevtech** [comment]
Should I send you the whole folder of this project..?

**Comment by sumitdevtech** [comment]
Hello, Patrick,
Please help me solve this issue....

**Comment by PatrickAlphaC** [comment]
Odd... I'm not sure what you're doing wrong...

If you directly git clone this repo, do you still get the error?

**Comment by sumitdevtech** [comment]
Yes, then also I am getting the error.
