### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2654: character maps to <undefined>

### ISSUE THREAD

**Issue by sagara11** [PatrickAlphaC/smartcontract-lottery#22]
When i run integration test on rinkeby network, i keep receiving this error. Can anyone help me?
The scripts I ran: brownie test -k test_can_pick_winner --network rinkeby
Here is my source code: 
![image](https://user-images.githubusercontent.com/50282671/145682589-cdeeb60f-be31-4b5f-8da9-033e9ef922a1.png)
Error:
![image](https://user-images.githubusercontent.com/50282671/145682603-eb17c4e8-0b8c-4eda-b4c8-e732b79e12b7.png)

**Comment by PatrickAlphaC** [comment]
Can you please make this a stackoverflow question, and tag it with `brownie`? Also, please don't use screenshot, but format your code.
