### ISSUE TITLE
The recentWinner is 0x0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by sagara11** [PatrickAlphaC/smartcontract-lottery#23]
Even though i set up time.sleep(60) and my source code looks like the same with the course, and i deploy successfully my scripts/deploy.py file but it still returns The recentWinner is 0x0000000000000000000000000000000000000000.
Can anyone help me pls?
![image](https://user-images.githubusercontent.com/50282671/145683225-d11e8271-c092-4140-9235-5995cc42efe9.png)
![image](https://user-images.githubusercontent.com/50282671/145683240-f2d617c6-3859-479f-a277-a5137475c88c.png)

**Comment by yrraadi-io** [comment]
Hey I'm facing the exact same issue, and I'm not able to figure out why. Please let me know if you find a solution.
Thanks.

**Comment by yrraadi-io** [comment]
Hey,
So I just figured it out. There is no issue, the smart contract takes a little time to update its state variable value, so just give it some time and recheck.
Hope this helps

**Comment by dnly09** [comment]
I got the same issue and waited as @yrraadi-io suggested - this fixed my issue. Reading the recentWinner on etherscan shows that some new account is there instead of the 0x000... I guess this means that brownie requires more than 1 minute of sleeping to receive the new winner.

**Comment by sagara11** [comment]
@yrraadi-io @dnly09 thanks guys it actually works!!!
