### ISSUE TITLE
fulfillRandomness is not being called after calling requestRandomness

### ISSUE THREAD

**Issue by mookund** [PatrickAlphaC/smartcontract-lottery#26]
The integration test is failing for me. Lastly, I literally copied all major code files from the git hub repo itself. For debugging I tried putting false require statements in fulfillRandomness function and the code didn't reach that snippet ever. I tried increasing the sleep time as well. 
The recentWinner()  call throws a 0 always that's how I got suspicious about it not getting into fulfillRandomness.
![Screenshot from 2021-12-19 16-11-41](https://user-images.githubusercontent.com/18279448/146672122-402c7bfa-8df7-47c6-a04d-3f0640519aa7.png)

**Comment by mookund** [comment]
https://github.com/mookund/LOTTERY  I have pushed all relevant code here

**Comment by PatrickAlphaC** [comment]
Can you increase the timeout from 60 to 180?

**Comment by mookund** [comment]
Hi, I tried doing that as well. Should I increase it further more?

**Comment by mookund** [comment]
Update 300 secs worked for me
