### ISSUE TITLE
FAILED tests/test_lottery.py::test_get_entrance_fee - brownie.exceptions.VirtualMachineError: revert 

### ISSUE THREAD

**Issue by willliuwillliu** [PatrickAlphaC/smartcontract-lottery#28]
I've been trying to debug this for 2 hours now and I want to cry. Please help!

I'm pretty sure this error has something to do with not being able to ingest the price feed properly.

I know this because if I return a hardcoded price from `getEntranceFee`, there is no error. This means the error has to be coming from `ethUsdPriceFeed.latestRoundData()`.

I have also tried to run this from a script. The contract deploys just fine, but the error occurs when `lottery.getEntranceFee()` runs. 

I'm almost certain I'm setting up my mainnet-fork correctly as well, here's the command I'm using: 
`brownie networks add development mainnet-fork cmd=ganache-cli host=http://127.0.0.1 fork=https://eth-mainnet.alchemyapi.io/v2/9lDVe3PdFhBWSWLvZioKCCOU38WfB0bo accounts=10 mnemonic=brownie port=8545`

The contract deployments are showing up in ganache and the RPC server appears to be configured correctly
<img width="1200" alt="Screen Shot 2022-01-02 at 4 57 44 PM" src="https://user-images.githubusercontent.com/55903529/147890495-4010484c-832b-4793-8aa2-282b89e4947e.png">

This is the error from the test: 
```

    def test_get_entrance_fee():
        account = accounts[0]
        lottery = Lottery.deploy(
            config["networks"][network.show_active()]["eth_usd_price_feed"],
            {"from": account},
        )
>       print(lottery.getEntranceFee())
E       brownie.exceptions.VirtualMachineError: revert

tests/test_lottery.py:10: VirtualMachineError
```

Below is the error I get when I run it from a script
```
Running 'scripts/test.py::main'...
mainnet-fork
Transaction sent: 0x8b7d058d0c2e8f8586faa8f5a099805af9f7ed05dd70c03025d277f17b73d9ca
  Gas price: 0.0 gwei   Gas limit: 6721975   Nonce: 26
  Lottery.constructor confirmed   Block: 29   Gas used: 195235 (2.90%)
  Lottery deployed at: 0x8A8b6e58D54038eF0f145800bB72f4bdA5a6Dda7

  File "brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/test.py", line 10, in main
    print(lottery.getEntranceFee())
  File "brownie/network/multicall.py", line 115, in _proxy_call
    result = ContractCall.__call__(*args, **kwargs)  # type: ignore
  File "brownie/network/contract.py", line 1665, in __call__
    return self.call(*args, block_identifier=block_identifier)
  File "brownie/network/contract.py", line 1461, in call
    raise VirtualMachineError(e) from None
VirtualMachineError: revert
```

test_lottery.py
```
from brownie import Lottery, accounts, config, network


def test_get_entrance_fee():
    account = accounts[0]
    lottery = Lottery.deploy(
        config["networks"][network.show_active()]["eth_usd_price_feed"],
        {"from": account},
    )
    print(lottery.getEntranceFee())
    assert lottery.getEntranceFee() > 0
```
brownie-config.yaml
```
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
networks:
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
```

Lottery.sol
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.6 ;
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";

contract Lottery {
    address payable[] public players;
    uint256 public usdEntryFee;
    AggregatorV3Interface internal ethUsdPriceFeed;

    constructor(address _priceFeedAddress) public {
        usdEntryFee = 50 * (10**18);
        ethUsdPriceFeed = AggregatorV3Interface(_priceFeedAddress);
    }

    function enter() public payable {
        // 50 min
        // players.push(msg.sender);
    }
    function getEntranceFee() public view returns (int256) {
        (
            uint80 roundID, 
            int256 price,
            uint startedAt,
            uint timeStamp,
            uint80 answeredInRound
        ) = ethUsdPriceFeed.latestRoundData();
        return price;
    }
    function startLottery() public {}
    function endLottery() public {}
}
```

**Comment by aleama98** [comment]
@willliuwillliu I had your same problem. I resolved it by: 

1. checking that I was not having any ganache/ganache-cli running
2.  delete the mainnet-fork `brownie networks delete mainnet-fork`
3. re create the mainnet-fork `brownie networks add development mainnet-fork cmd=ganache-cli host=http://127.0.0.1 fork=<link to your api> accounts=10 mnemonic=brownie port=8545`

Hope this will help you :)

**Comment by willliuwillliu** [comment]
@aleama98 that did the trick! You reminded me that Patrick did tell us ganache had to be closed but I completely forgot about that. Thanks a bunch! Closing this out.

**Comment by IamSiddharthChoudhary** [comment]
Done the same but still having this error...

**Comment by IamSiddharthChoudhary** [comment]
Done the same but still having this error...
