### ISSUE TITLE
return tx["from"].transfer( AttributeError: 'function' object has no attribute 'transfer'

### ISSUE THREAD

**Issue by gYomii** [PatrickAlphaC/smartcontract-lottery#31]
Hello, it seems that my LinkToken.sol returns an issue while I run scripts/deploy_lottery.py. The issue occurs after the writing of the start_lottery( ) in deploy.py which is run perfecly, this is when I write the code of the  enter_lottery() in deploy.py. I guess the attirbute of transfer function in LinkToken.sol doesn't work.

return tx["from"].transfer(
AttributeError: 'function' object has no attribute 'transfer'

thank you for your help

**Comment by PatrickAlphaC** [comment]
Can you please edit your issue to have:

1. Your script you're running (deploy_lottery.py)
2. Your directory layout
3. Your lottery code

**Comment by gYomii** [comment]
Yes sure, I see, I've checked the directory layout and, yes, I'll chek twice...

**Comment by gYomii** [comment]
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.6;
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@chainlink/contracts/src/v0.6/VRFConsumerBase.sol";

contract Lottery is VRFConsumerBase, Ownable {
    address payable[] public players;
    address payable public recentWinner;
    uint256 public randomness;
    uint256 public usdEntryFee;
    AggregatorV3Interface internal ethUsdPriceFeed;
    //0,1,2

    enum LOTTERY_STATE {
        OPEN,
        CLOSED,
        CALCULATING_WINNER
    }
    LOTTERY_STATE public lottery_state;
    uint256 public fee;
    bytes32 public keyhash;

    constructor(
        address _priceFeedAddress,
        address _vrfCoordinator,
        address _link,
        uint256 _fee,
        bytes32 _keyhash
    ) public VRFConsumerBase(_vrfCoordinator, _link) {
        usdEntryFee = 50 * (10**18);
        ethUsdPriceFeed = AggregatorV3Interface(_priceFeedAddress);
        lottery_state = LOTTERY_STATE.CLOSED;
        fee = _fee;
        keyhash = _keyhash;
    }

    function enter() public payable {
        // inscription et entrée dans le jeu
        // 50$ minimum
        require(lottery_state == LOTTERY_STATE.OPEN);
        require(msg.value >= getEntranceFee(), "not enough eth!");
        players.push(msg.sender);
    }

    function getEntranceFee() public view returns (uint256) {
        // envoyer des commissions
        (, int256 price, , , ) = ethUsdPriceFeed.latestRoundData();
        uint256 adjustedPrice = uint256(price) * 10**10; //18 decimals
        // $50, $2 000 /eth
        // 50*100000/2000
        uint256 costToEnter = (usdEntryFee * 10**18) / adjustedPrice;
        return costToEnter;
    }

    function startLottery() public onlyOwner {
        require(
            lottery_state == LOTTERY_STATE.CLOSED,
            "Can't start a new lottery yet!"
        );
        lottery_state = LOTTERY_STATE.OPEN;
    } // démarrer la lotterie sur commande de l'administrateur

    function endLottery() public onlyOwner {
        // uint256(
        //     keccack256(
        //         abi.encodePacked(
        //             nonce, // nonce is predicitble (aka, transaction number)
        //             msg.sender, //msg.sender is predicttable
        //             block.difficulty, // can be manipulated by the miners
        //             block.timestamp // is predictible
        //         )
        //     )
        // ) % players.length;
        lottery_state = LOTTERY_STATE.CALCULATING_WINNER;
        bytes32 requestId = requestRandomness(keyhash, fee);
    } // arrêter la loterie

    function fulfillRandomness(bytes32 _requestId, uint256 _randomness)
        internal
        override
    {
        require(
            lottery_state == LOTTERY_STATE.CALCULATING_WINNER,
            "YOU AREN'T HERE YET"
        );
        require(_randomness > 0, "random-not-found");
        uint256 indexOfWinner = _randomness % players.length;
        recentWinner = players[indexOfWinner];
        recentWinner.transfer(address(this).balance);
        //reset
        players = new address payable[](0);
        lottery_state = LOTTERY_STATE.CLOSED;
        randomness = _randomness;

        //7 players
        //22
        //22% 7 = 1
        //7 * 3 = 21
        // 7 * 4 = 28
    }
}

**Comment by gYomii** [comment]
Something wrong here right?

**Comment by gYomii** [comment]
Forgot () sorry ....

**Comment by PatrickAlphaC** [comment]
Nice work :)
