### ISSUE TITLE
add verify: False

### ISSUE THREAD

**Issue by gYomii** [PatrickAlphaC/smartcontract-lottery#32]
in 
https://github.com/PatrickAlphaC/smartcontract-lottery/blob/4bf418479b3fa45bc51479c1f557d952186c765c/brownie-config.yaml#L23
suggest add verify: False

**Comment by PatrickAlphaC** [comment]
Oo! That's great. Can you make a PR?

**Comment by PatrickAlphaC** [comment]
Added here: https://github.com/PatrickAlphaC/smartcontract-lottery/pull/49
