### ISSUE TITLE
brownie compile connection error

### ISSUE THREAD

**Issue by catinsourcream** [PatrickAlphaC/smartcontract-lottery#33]
Hi,

When executing a brownie compile for Lottery contract in VScode terminal I get the error below:

ConnectionError: HTTPSConnectionPool(host='codeload.github.com', port=443): Max retries exceeded with url: /smartcontractkit/chainlink-brownie-contracts/legacy.zip/refs/tags/1.1.1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020A4E9B5540>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

When saving Lottery.sol in VScode I have this error:
Source "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol" not found: File import callback not supported

I don't have access to https://codeload.github.com/ using my default internet provider.

Any help would be much appreciated.

**Comment by PatrickAlphaC** [comment]
Could you read this and let me know if that solves it? 

https://stackoverflow.com/questions/2972600/no-connection-could-be-made-because-the-target-machine-actively-refused-it

**Comment by catinsourcream** [comment]
Hi Patrick,
After the trace route of "codeload.github.com" it turned out that "codeload.github.com" was somehow set for a localhost on my laptop.
Adding "140.82.113.9   codeload.github.com" to a Windows hosts file solved the problem.
Anyway thanks for your help.
Take care.
