### ISSUE TITLE
Rinkeby deployment

### ISSUE THREAD

**Issue by Bubbuka** [PatrickAlphaC/smartcontract-lottery#37]
Hi!
I'm almost finished with the lottery part of the course, but I seem to be stuck at the rinkeby deployment phase.
Everything works fine and I get all the correct messages but when announcing the winner i get 0x00000000000000.. is the new winner, and when i explore in the etherscan of the contract I can see that i can enter the lottery fine, but a random number is not given and a winner is not selected, even though I don't get a random-not-found error. Here is the contract address: 0x726aE3209E0B116bcC65fdF6743129323bD285f3

I've been looking for hours now for an error in my endLottery and fulfillRandomness functions as I can see in the etherscan that the lottery state is 2, so it must be stuck at that part of the code but everything seems exactly as the repository files and since I have no actual error I cannot tell where I might be going wrong.
Thanks for the help, the course is amazing, I'm really looking forward to the next part, but I want to do it properly.

**Comment by PatrickAlphaC** [comment]
Hmm... Glad the course is helping!

Odd that part is not working... I mean, it _is_ just a testnet integration test so it's not the end of the world if you skip. Testnets can be finicky since they are free services.

It looks right... And I can see the Chainlink VRF node returning numbers... It's hard to test... do all your local tests pass?

**Comment by Bubbuka** [comment]
Yes, all the local test pass but now that I ran everything again I see that have a similar problem in the integration test, when asserting  lottery.recentWinner() == account I get an error because 0x0000... is not == to my account, I've tried changing the waiting time to give it an opportunity to respond but it's not helping.
Thank you for the response! I think I will go on for now with the course and I will revisit the problem when I need to deploy something again, maybe its a testnet problem like you said.

**Comment by Bubbuka** [comment]
I made it work! I think... I played around a little with the scripts with no change and then created a new infura project id with no success at first but at the third try it worked! I have no idea what it was at the end. Thanks again for the support!

**Comment by PatrickAlphaC** [comment]
Awesome!
