### ISSUE TITLE
Multiple Errors 

### ISSUE THREAD

**Issue by CrypptoPaul** [PatrickAlphaC/smartcontract-lottery#39]
CompilerError: solc returned the following errors:

contracts/Lottery.sol:82:9: TypeError: Function has override specified but does not override anything.
        override
        ^------^

contracts/Lottery.sol:10:1: TypeError: Contract "Lottery" should be marked as abstract.
contract Lottery is VRFConsumerBase, Ownable {
^ (Relevant source part starts here and spans across multiple lines).
C:/Users/user/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/VRFConsumerBase.sol:121:3: Missing implementation:
  function fulfillRandomness(bytes32 requestId, uint256 randomness)
  ^ (Relevant source part starts here and spans across multiple lines).

**Comment by CrypptoPaul** [comment]
I would be extremely grateful for some help here, I am completely lost

**Comment by PatrickAlphaC** [comment]
Can you add your Lottery.sol code?

**Comment by allsoldev** [comment]
I had a similar issue, after investigating I found that I was overriding the wrong function. Please recheck or share the code

**Comment by mattsegura** [comment]
> I would be extremely grateful for some help here, I am completely lost

could you please post your code

**Comment by PatrickAlphaC** [comment]
Closing due to stale
