### ISSUE TITLE
[ERROR] - testing on Rinkeby - test_lottery_integration.py

### ISSUE THREAD

**Issue by uroskg99** [PatrickAlphaC/smartcontract-lottery#4]
When I tried to test on Rinkeby I received this error:

scripts\help.py:75: in fund_with_link_token
    tx = link_token.transfer(contract_address, amount, {"from": account})
..\..\..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\contract.py:1693: in __call__
    return self.transact(*args)
..\..\..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\contract.py:1566: in transact
    return tx["from"].transfer(
..\..\..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\account.py:642: in transfer
    receipt, exc = self._make_transaction(
..\..\..\appdata\local\programs\python\python39\lib\site-packages\brownie\network\account.py:725: in _make_transaction
    raise VirtualMachineError(e) from None

After that there is ValueError:

Gas estimation failed: 'invalid opcode: opcode 0xfe not defined'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

Can You help me with this problem?

**Comment by PatrickAlphaC** [comment]
Could you send the code of your:

1. Script you're running
2. The exact command you're using
3. The full output of your error
4. Your file structure
5. Your contract that you're deploying

**Comment by PatrickAlphaC** [comment]
Also, let me know if this helps: https://ethereum.stackexchange.com/questions/90807/im-getting-invalid-opcode-opcode-0xfe-not-defined-when-trying-to-estimate-t

**Comment by uroskg99** [comment]
It helped me to fix the previous problem, but now when I try test with this command:

brownie test -k test_can_pick_winner --network rinkeby -s

It returns that my lottery.recentWinner() is "0x0000..0000", seems like function end_lottery() has never been called. Here is my log when I test it:

Waiting for https://api-rinkeby.etherscan.io/api to process contract...
Verification submitted successfully. Waiting for result...
Verification complete. Result: Pass - Verified
Contract deployed
Contract fund
tests/test_lottery_integration.py::test_can_pick_winner FAILED
tests/test_lottery_unit.py::test_can_pick_winner SKIPPED

========================================================================================================== FAILURES ========================================================================================================== 
____________________________________________________________________________________________________ test_can_pick_winner ____________________________________________________________________________________________________ 

    def test_can_pick_winner():
        if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
            pytest.skip()
        lottery = deploy_lottery()
        account = get_account()
        lottery.startLottery({"from": account})
        lottery.enter({"from": account, "value": lottery.getEntranceFee()})
        lottery.enter({"from": account, "value": lottery.getEntranceFee()})
        lottery.enter({"from": account, "value": lottery.getEntranceFee()})
        fund_with_link_token(lottery)
        lottery.endLottery({"from": account})
        time.sleep(60)
>       assert lottery.lastWinner() == account.address
E       AssertionError: assert '0x0000000000...0000000000000' == '0x421741C46b...558Af51305bBf'
E         - 0x421741C46b6AcFd320F2046BB3d558Af51305bBf
E         + 0x0000000000000000000000000000000000000000

tests\test_lottery_integration.py:24: AssertionError
================================================================================================== short test summary info =================================================================================================== 
FAILED tests/test_lottery_integration.py::test_can_pick_winner - AssertionError: assert '0x0000000000...0000000000000' == '0x421741C46b...558Af51305bBf'

**Comment by uroskg99** [comment]
Here are my deploy.py and help.py scripts.

from scripts.help import get_account, get_contract, fund_with_link_token
from brownie import Lottery, network, config
import time


def deploy_lottery():
    account = get_account()
    lottery = Lottery.deploy(
        get_contract("eth_usd_price_feed").address,
        get_contract("vrf_coordinator").address,
        get_contract("link_token").address,
        config["networks"][network.show_active()]["fee"],
        config["networks"][network.show_active()]["keyhash"],
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify", False),
    )
    print("Contract deployed")
    return lottery


def start_lottery():
    account = get_account()
    lottery = Lottery[-1]
    starting_tx = lottery.startLottery({"from": account})
    starting_tx.wait(1)
    print("Lottery started")


def enter_lottery():
    account = get_account()
    lottery = Lottery[-1]
    value = lottery.getEntranceFee() + 10000000
    tx = lottery.enter({"from": account, "value": value})
    tx.wait(1)
    print("Successfuly joined lottery")


def end_lottery():
    account = get_account()
    lottery = Lottery[-1]
    tx = fund_with_link_token(lottery)
    tx.wait(1)
    ending_transaction = lottery.endLottery({"from": account})
    ending_transaction.wait(1)
    time.sleep(60)
    print(f"{lottery.lastWinner()} is winner!")


def main():
    deploy_lottery()
    start_lottery()
    enter_lottery()
    end_lottery()

**Comment by uroskg99** [comment]
Help.py script here: 

from brownie import (
    accounts,
    network,
    config,
    MockV3Aggregator,
    VRFCoordinatorMock,
    LinkToken,
    Contract,
)

FORKED_LOCAL_ENVIRONMENTS = ["mainnet-fork", "mainnet-fork-dev"]
LOCAL_BLOCKCHAIN_ENVIRONMENTS = ["development", "ganache-local"]


def get_account(index=None, id=None):
    if index:
        return accounts[index]
    if id:
        return accounts.load(id)
    if (
        network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS
        or network.show_active() in FORKED_LOCAL_ENVIRONMENTS
    ):
        return accounts[0]

    return accounts.add(config["wallets"]["from_key"])


contract_to_mock = {
    "eth_usd_price_feed": MockV3Aggregator,
    "vrf_coordinator": VRFCoordinatorMock,
    "link_token": LinkToken,
}


def get_contract(contract_name):

    contract_type = contract_to_mock[contract_name]
    if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        if len(contract_type) <= 0:
            deploy_mocks()
        contract = contract_type[-1]
    else:
        contract_address = config["networks"][network.show_active()][contract_name]
        contract = Contract.from_abi(
            contract_type._name, contract_address, contract_type.abi
        )

    return contract


DECIMALS = 8
INITIAL_VALUE = 200000000000


def deploy_mocks(decimals=DECIMALS, initial_value=INITIAL_VALUE):
    account = get_account()
    MockV3Aggregator.deploy(decimals, initial_value, {"from": account})
    link_token = LinkToken.deploy({"from": account})
    VRFCoordinatorMock.deploy(link_token.address, {"from": account})
    print("Mock deployed")


def fund_with_link_token(
    contract_address, account=None, link_token=None, amount=100000000000000000
):
    account = account if account else get_account()
    link_token = link_token if link_token else get_contract("link_token")
    tx = link_token.transfer(contract_address, amount, {"from": account})
    tx.wait(1)
    print("Contract fund")
    return tx

**Comment by uroskg99** [comment]
Solved

**Comment by PatrickAlphaC** [comment]
Nice! What was the issue?

**Comment by uroskg99** [comment]
The issue was that my contract needed little more time to calculate winner. I have figured it out when I went to testnet the day later and I saw that address of the last winner has changed 🙂

**Comment by abhishekchaturvedi10** [comment]
I am getting the same error. Please tell how can it be resolved?

**Comment by PatrickAlphaC** [comment]
Nice, thanks for following up!
