### ISSUE TITLE
Lesson 7: AttributeError Contract 'Lottery' object has no attribute 'getEntranceFee' '

### ISSUE THREAD

**Issue by mattsegura** [PatrickAlphaC/smartcontract-lottery#43]
Feel like I typed something wrong 

**Lottery.sol**
<img width="823" alt="image" src="https://user-images.githubusercontent.com/61678138/155073911-019de636-416e-405f-a575-9c3ea0424b66.png">

**test_lottery.py**
<img width="794" alt="image" src="https://user-images.githubusercontent.com/61678138/155073867-21c1d200-4768-4fc9-9469-902e03e5ace6.png">

**brownie-config.yaml**
<img width="656" alt="image" src="https://user-images.githubusercontent.com/61678138/155073811-7d3b1e32-0a3b-4012-9990-1dde488b0e2d.png">

**error** when doing 
`brownie test --network mainnet-fork`
<img width="778" alt="image" src="https://user-images.githubusercontent.com/61678138/155074034-fba5c639-375b-45b4-8bc1-6652d44e1d37.png">

**Comment by PatrickAlphaC** [comment]
Likely a typo on your lottery function, can you check?

**Comment by salamisami** [comment]
You wrote "Entrence" instead of "Entrance"
