### ISSUE TITLE
test_lottery_unit with more than 3 entrants 

### ISSUE THREAD

**Issue by CGYoung1040** [PatrickAlphaC/smartcontract-lottery#44]
When I try to run the last unit test (test_can_pick_winner_correctly()) with more than 3 accounts in the lottery (like in the video) the test fails with the following error:

`E       AssertionError: assert '0x33A4622B82D4c04a53e170c638B944ce27cffce3' == <Account '0x66aB6D9362d4F35596279692F0251Db635165871'>`
`E        +  where '0x33A4622B82D4c04a53e170c638B944ce27cffce3' = <ContractCall 'recentWinner()'>()`
`E        +    where <ContractCall 'recentWinner()'> = <Lottery Contract '0xe65A7a341978d59d40d30FC23F5014FACB4f575A'>.recentWinner`

The last assert statement `account.balance() == starting_balance_of_account + balance_of_lottery` also fails:

`E       AssertionError: assert 99925000000000000000 == (99925000000000000000 + 100000000000000000)`
`E        +  where 99925000000000000000 = <bound method PublicKeyAccount.balance of <Account '0x66aB6D9362d4F35596279692F0251Db635165871'>>()`
`E        +    where <bound method PublicKeyAccount.balance of <Account '0x66aB6D9362d4F35596279692F0251Db635165871'>> = <Account '0x66aB6D9362d4F35596279692F0251Db635165871'>.balance`

This is probably a noob question but I can't wrap my head around why you can't enter the lottery with more than 3 players since the winner is picked using `uint256 indexOfWinner = _randomness % players.length` and nothing here is hardcoded to 3.

**Comment by mattsegura** [comment]
> When I try to run the last unit test (test_can_pick_winner_correctly()) with more than 3 accounts in the lottery (like in the video) the test fails with the following error:
> 
> `E AssertionError: assert '0x33A4622B82D4c04a53e170c638B944ce27cffce3' == <Account '0x66aB6D9362d4F35596279692F0251Db635165871'>` `E + where '0x33A4622B82D4c04a53e170c638B944ce27cffce3' = <ContractCall 'recentWinner()'>()` `E + where <ContractCall 'recentWinner()'> = <Lottery Contract '0xe65A7a341978d59d40d30FC23F5014FACB4f575A'>.recentWinner`
> 
> The last assert statement `account.balance() == starting_balance_of_account + balance_of_lottery` also fails:
> 
> `E AssertionError: assert 99925000000000000000 == (99925000000000000000 + 100000000000000000)` `E + where 99925000000000000000 = <bound method PublicKeyAccount.balance of <Account '0x66aB6D9362d4F35596279692F0251Db635165871'>>()` `E + where <bound method PublicKeyAccount.balance of <Account '0x66aB6D9362d4F35596279692F0251Db635165871'>> = <Account '0x66aB6D9362d4F35596279692F0251Db635165871'>.balance`
> 
> This is probably a noob question but I can't wrap my head around why you can't enter the lottery with more than 3 players since the winner is picked using `uint256 indexOfWinner = _randomness % players.length` and nothing here is hardcoded to 3.

in uint256, 
u - means unsigned which means it can only represent positive int val
int - means integer
256 - 256 max storage
make sure that your initializations are the same value type; everything needs to be unit256 values

**Comment by PatrickAlphaC** [comment]
The tests are looking specifically for 3 people to enter, you'd have to adjust the whole test for more people to enter, as the winner will be different, and the balance will be different.

**Comment by CGYoung1040** [comment]
> in uint256,
u - means unsigned which means it can only represent positive int val
int - means integer
256 - 256 max storage
make sure that your initializations are the same value type; everything needs to be unit256 values

I'm not sure what you're referring to. Where did I not use uint256? And what does that have to do with my question?

> The tests are looking specifically for 3 people to enter, you'd have to adjust the whole test for more people to enter, as the winner will be different, and the balance will be different.

Ok thanks. Where in the test do I see that it's designed for 3 entrants? Appreciate your help
