### ISSUE TITLE
The current code does not compile

### ISSUE THREAD

**Issue by jarekdrabek** [PatrickAlphaC/smartcontract-lottery#47]
If I compile with version 0.6.6 it 

> contracts/test/LinkToken.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.6.6+commit.6c089d02.Darwin.appleclang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.11;
^----------------------^

**Comment by PatrickAlphaC** [comment]
This is just a linting issue with your solidity extension. If:

```
brownie compile
```

errors, that's an issue.

**Comment by jarekdrabek** [comment]
That was the out put of 
`brownie compile`
indeed
