### ISSUE TITLE
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'poll' 

### ISSUE THREAD

**Issue by rholderfield** [PatrickAlphaC/smartcontract-lottery#5]
Hi,

I'm wondering if anyone knows how to resolve this error.

$ brownie test --network mainnet-fork
INFO: Could not find files for the given pattern(s).
Brownie v1.16.3 - Python development framework for Ethereum

=========================== test session starts ===========================
platform win32 -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0       
rootdir: C:\Users\rhold\Desktop\demos\smartcontract-lottery
plugins: eth-brownie-1.16.3, hypothesis-6.17.4, forked-1.3.0, xdist-1.34.0, 
web3-5.23.1
collected 1 item                                                            

Launching 'ganache-cli.cmd --accounts 10 --fork https://eth-mainnet.alchemyapi.io/v2/***** --mnemonic brownie --port 8545 --hardfork istanbul'...
Terminating local RPC client...
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 641, in perform_collect
INTERNALERROR>     hook.pytest_collection_finish(session=self)
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\test\lib\site-packages\brownie\test\managers\runner.py", line 258, in pytest_collection_finish
INTERNALERROR>     brownie.network.connect(CONFIG.argv["network"])          \lib\site-packages\brownie\netw
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\main.py", line 50, in connect
INTERNALERROR>     rpc.launch(active["cmd"], **active["cmd_settings"])      \lib\site-packages\brownie\netw
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\network\rpc\__init__.py", line 95, in launch     
INTERNALERROR>     raise RPCConnectionError(cmd, self.process, uri)         \lib\site-packages\brownie\exce
INTERNALERROR>   File "C:\Users\rhold\AppData\Local\Programs\Python\Python39\lib\site-packages\brownie\exceptions.py", line 41, in __init__             }"
INTERNALERROR>     f"\n\nCommand: {cmd}\nURI: {uri}\nExit Code: {proc.poll()}"
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'poll' 

I see the transaction hitting Alchemy and haven't found much info on google about the error.

https://github.com/rholderfield/smartcontract-lottery

Thanks!

**Comment by rholderfield** [comment]
I'm not sure what the issue was, but I decided to delete the brownie mainnet-fork and re-add it, and it started working. When I first reported the issue, the only method hitting alchemy was eth_getTransactionCount. After deleting and adding back, I saw other methods hitting alchemy, and the test was successful.

**Comment by PatrickAlphaC** [comment]
Nice work!!
