### ISSUE TITLE
GetPassWarning: Can not control echo on the terminal.

### ISSUE THREAD

**Issue by saidalbouti99** [PatrickAlphaC/smartcontract-lottery#50]
Hello, I cannot run unit test on my terminal. The terminal looks like this:

`tests\test_lottery_unit.py:17:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
scripts\deploy_lottery.py:5: in deploy_lottery
    account = get_account(id="freecodecamp")
scripts\helpful_scripts.py:12: in get_account
    return accounts.load(id)
C:\Python\Python310\lib\site-packages\brownie\network\account.py:221: in load
    password or getpass(f'Enter password for "{json_file.stem}": '),
C:\Python\Python310\lib\getpass.py:100: in win_getpass
    return fallback_getpass(prompt, stream)
C:\Python\Python310\lib\getpass.py:126: in fallback_getpass
    return _raw_input(prompt, stream)
C:\Python\Python310\lib\getpass.py:146: in _raw_input
    line = input.readline()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_pytest.capture.DontReadFromInput object at 0x0000016F68E81B10>, args = ()

    def read(self, *args):
>       raise OSError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

C:\Python\Python310\lib\site-packages\_pytest\capture.py:217: OSError
------------------------------------------------------------- Captured stderr call -------------------------------------------------------------- 
Warning: Password input may be echoed.
Enter password for "freecodecamp":
=============================================================== warnings summary ================================================================ 
tests/test_lottery_unit.py::test_get_entrance_fee
  C:\Python\Python310\lib\getpass.py:100: GetPassWarning: Can not control echo on the terminal.
    return fallback_getpass(prompt, stream)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================================ short test summary info ============================================================ 
FAILED tests/test_lottery_unit.py::test_get_entrance_fee - OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.    
========================================================= 1 failed, 1 warning in 7.54s ========================================================== `

**Comment by PatrickAlphaC** [comment]
Can you try to format this with 3 backticks ```? I can't really understand what command you ran or what's going on here.
