### ISSUE TITLE
Lesson 7: same account starts the lottery and enters two consecutive times

### ISSUE THREAD

**Issue by n4n0b1t3** [PatrickAlphaC/smartcontract-lottery#53]
https://github.com/PatrickAlphaC/smartcontract-lottery/blob/main/tests/test_lottery_integration.py#L12
test_can_pick_winner() of the integration test, enters the lottery two times with the same account which started it. Can you please check this, it's exactly the code from the video, but I believe this makes no sense.

```
    account = get_account()
    lottery.startLottery({"from": account})
    lottery.enter({"from": account, "value": lottery.getEntranceFee()})
    lottery.enter({"from": account, "value": lottery.getEntranceFee()})
```

**Comment by PatrickAlphaC** [comment]
Yep!

It doesn't really matter who enters, you could just as easily make it anyone. 

But you're right, some "better" tests would involve different people!
