### ISSUE TITLE
test_can_pick_winner_correctly bug

### ISSUE THREAD

**Issue by blockdjango** [PatrickAlphaC/smartcontract-lottery#6]
https://github.com/PatrickAlphaC/smartcontract-lottery/blob/8876d504b707883f148f9a8cac7a287b90d0f5df/tests/test_lottery_unit.py#L81-L82

I think these [two lines of code](https://github.com/PatrickAlphaC/smartcontract-lottery/blob/8876d504b707883f148f9a8cac7a287b90d0f5df/tests/test_lottery_unit.py#L81-L82
) should go before we do [callBackWithRandomness](https://github.com/PatrickAlphaC/smartcontract-lottery/blob/8876d504b707883f148f9a8cac7a287b90d0f5df/tests/test_lottery_unit.py#L78)(...)

Otherwise we're actually setting the `starting_balance_of_account` as the _ending balance_ and the `balance_of_lottery` to 0 _(ending balance.)_ The test still passes because the sum total of the the _winner's account balance_ == _the lottery balance_ + _the winner's account_ balance, before or after the funds are dispersed to the winner.

**Comment by PatrickAlphaC** [comment]
I think you're right! This is a bit confusing on the test. Could you draft a PR to fix?
