### ISSUE TITLE
Error at requestRandomness

### ISSUE THREAD

**Issue by tolivern** [PatrickAlphaC/smartcontract-lottery#67]
Hi! I am trying to deploy Lottery.sol and everything is fine until I have to call the requestRandomness function, I get an error without much explanation... What could be going on here? Thanks! (I´m new at programming, probably it is something obvious...)

(My code is exactly the same as Lottery.sol in this repository)

SmartcontractLotteryProject is the active project.

Launching 'ganache-cli.cmd --accounts 10 --hardfork istanbul --gasLimit 12000000 --mnemonic brownie --port 8545'...

Running 'scripts\deploy_lottery.py::main'...
Transaction sent: 0x24d70cb6f9b461bf75c8a198116ba6a95d499a9d64d16605eaa5ac3c356de1f7
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 0
  MockV3Aggregator.constructor confirmed   Block: 1   Gas used: 430659 (3.59%)
  MockV3Aggregator deployed at: 0x3194cBDC3dbcd3E11a07892e7bA5c3394048Cc87

MockV3Aggregator deployed!
Transaction sent: 0x076a2c1837406d129d2d2665a4d662b9087a59e481812d2e3973839e26997331
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 1
  LinkToken.constructor confirmed   Block: 2   Gas used: 669136 (5.58%)
  LinkToken deployed at: 0x602C71e4DAC47a042Ee7f46E0aee17F94A3bA0B6

LinkToken deployed!
Transaction sent: 0x01030f154277021ef9fdf49f02db588965f2fa7448608eeb8f2d743ce9c5cf84
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
  VRFCoordinatorMock.constructor confirmed   Block: 3   Gas used: 276395 (2.30%)
  VRFCoordinatorMock deployed at: 0xE7eD6747FaC5360f88a2EFC03E00d25789F69291

VRFCoordinatorMock deployed!
Transaction sent: 0x98edce7937c780c238d4f90966a17391075aa96123c25af92c9b5cfa716a0031
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 3
  Lottery.constructor confirmed   Block: 4   Gas used: 897156 (7.48%)
  Lottery deployed at: 0x6951b5Bd815043E3F842c1b026b0Fa888Cc2DD85

Deployed lottery!!
Transaction sent: 0x1f3629b4ccc88f7e9e8b4f9d7d7a0e3328610fafa9346bd79152467364540969
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 4
  Lottery.startLottery confirmed   Block: 5   Gas used: 28902 (0.24%)

  Lottery.startLottery confirmed   Block: 5   Gas used: 28902 (0.24%)

The lottery started!
Transaction sent: 0x5b64596a5f9cd13211b6833b38e428007458f07407f88374a7f8118edb1fd8c0
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 5
  Lottery.enter confirmed   Block: 6   Gas used: 70995 (0.59%)

  Lottery.enter confirmed   Block: 6   Gas used: 70995 (0.59%)

You entered the lottery!
Transaction sent: 0xe930a3aa6106d132e9479441011d896ee16f7f7c6a5feffcf02436337497410a
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 6
  LinkToken.transfer confirmed   Block: 7   Gas used: 51398 (0.43%)

  LinkToken.transfer confirmed   Block: 7   Gas used: 51398 (0.43%)

Contract funded with link!
  LinkToken.transfer confirmed   Block: 7   Gas used: 51398 (0.43%)

He vuelto del fund_with_link
Transaction sent: 0xe97361a7db515a30e3feac79b1e14d6e16abd3132949b17a82fbb83cd87bc619
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 7
  Lottery.endLottery confirmed (reverted)   Block: 8   Gas used: 11813033 (98.44%)

  File "C:\Users\teres\AppData\Roaming\Python\Python310\site-packages\brownie\_cli\run.py", line 49, in main
    return_value, frame = run(
  File "C:\Users\teres\AppData\Roaming\Python\Python310\site-packages\brownie\project\scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File ".\scripts\deploy_lottery.py", line 58, in main
    end_lottery()
  File ".\scripts\deploy_lottery.py", line 46, in end_lottery
    tx2 = lottery.endLottery({"from": account})
  File "C:\Users\teres\AppData\Roaming\Python\Python310\site-packages\brownie\network\contract.py", line 1693, in __call__
    return self.transact(*args)
  File "C:\Users\teres\AppData\Roaming\Python\Python310\site-packages\brownie\network\contract.py", line 1566, in transact
    return tx["from"].transfer(
  File "C:\Users\teres\AppData\Roaming\Python\Python310\site-packages\brownie\network\account.py", line 680, in transfer
    receipt._raise_if_reverted(exc)
  File "C:\Users\teres\AppData\Roaming\Python\Python310\site-packages\brownie\network\transaction.py", line 420, in _raise_if_reverted
    raise exc._with_attr(
**VirtualMachineError: revert
Trace step -1, program counter 2469:
  File "C:/Users/teres/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/VRFConsumerBase.sol", line 161, in VRFConsumerBase.requestRandomness:
    function requestRandomness(bytes32 _keyHash, uint256 _fee)
      internal returns (bytes32 requestId)**
    {
      LINK.transferAndCall(vrfCoordinator, _fee, abi.encode(_keyHash, USER_SEED_PLACEHOLDER));
      // This is the seed passed to VRFCoordinator. The oracle will mix this with
      // the hash of the block containing this request to obtain the seed/input
      // which is finally passed to the VRF cryptographic machinery.
Terminating local RPC client...

**Comment by PatrickAlphaC** [comment]
Looks like it's mad about `end_lottery`... 

Could you try again? Same issue?

**Comment by tolivern** [comment]
I tried something just to see what happens, I copied and compiled my own VRFConsumerBase.sol, instead of importing from chainlink. I got a different error, is this helpful?:

...
The lottery started!
Transaction sent: 0x5b64596a5f9cd13211b6833b38e428007458f07407f88374a7f8118edb1fd8c0
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 5
  Lottery.enter confirmed   Block: 6   Gas used: 70995 (0.59%)

  Lottery.enter confirmed   Block: 6   Gas used: 70995 (0.59%)

You entered the lottery!
Transaction sent: 0xe930a3aa6106d132e9479441011d896ee16f7f7c6a5feffcf02436337497410a
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 6
  LinkToken.transfer confirmed   Block: 7   Gas used: 51398 (0.43%)

  LinkToken.transfer confirmed   Block: 7   Gas used: 51398 (0.43%)

Contract funded with link!
  LinkToken.transfer confirmed   Block: 7   Gas used: 51398 (0.43%)

He vuelto del fund_with_link
Transaction sent: 0xe97361a7db515a30e3feac79b1e14d6e16abd3132949b17a82fbb83cd87bc619
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 7
  **Lottery.endLottery confirmed (reverted)   Block: 8   Gas used: 11813033 (98.44%)
        _fee,
        abi.encode(_keyHash, USER_SEED_PLACEHOLDER)**
    );
    // This is the seed passed to VRFCoordinator. The oracle will mix this with
    // the hash of the block containing this request to obtain the seed/input
    // which is finally passed to the VRF cryptographic machinery.
    uint256 vRFSeed = makeVRFInputSeed(
        _keyHash,
Terminating local RPC client...

**Comment by PatrickAlphaC** [comment]
Can you list your steps starting from you git cloning this repo? Like every line you run in your shell.

**Comment by tolivern** [comment]
Don´t worry, Patrick, I have moved on to the ERC20 part. I intend to repeat the whole course again when I finish, let´s see if I can get it right then. Thanks.

**Comment by tristanpeter** [comment]
Hi All,

Just an FYI, I had the exact same issue as this. I resolved it by adding the deploy_mocks.py script from the git repo. I'm not sure how I missed adding it, but anyway, it's working for me now after doing so.

[Deploy Mocks Script](https://github.com/PatrickAlphaC/smartcontract-lottery/blob/main/scripts/deploy_mocks.py)

Thanks
Tristan
