### ISSUE TITLE
fund_with_link question

### ISSUE THREAD

**Issue by blockdjango** [PatrickAlphaC/smartcontract-lottery#7]
https://github.com/PatrickAlphaC/smartcontract-lottery/blob/8876d504b707883f148f9a8cac7a287b90d0f5df/tests/test_lottery_unit.py#L74
vs.
https://github.com/PatrickAlphaC/smartcontract-lottery/blob/8876d504b707883f148f9a8cac7a287b90d0f5df/scripts/deploy_lottery.py#L43

`fund_with_link(lottery)` vs. `fund_with_link(lottery.address)`?

You pass in `lottery` on line 74 of the [unit test](https://github.com/PatrickAlphaC/smartcontract-lottery/blob/8876d504b707883f148f9a8cac7a287b90d0f5df/tests/test_lottery_unit.py#L74) instead of `lottery.address` as you did on line 43 in the [deploy script](https://github.com/PatrickAlphaC/smartcontract-lottery/blob/8876d504b707883f148f9a8cac7a287b90d0f5df/scripts/deploy_lottery.py#L43). The difference seems to be _**contract** vs. **contract address**_.

You also defined the `fund_with_link(contract_address, ... ) `method to take in a `contract_address` 
https://github.com/PatrickAlphaC/smartcontract-lottery/blob/8876d504b707883f148f9a8cac7a287b90d0f5df/scripts/helpful_scripts.py#L81-L82

Everything seems to work find either way but am I curious as to why you can do it either way.

P.S. Learning lots from the tutorial!

**Comment by PatrickAlphaC** [comment]
Great question!

Yes, this was an oversight on my end. Brownie is actually smart enough to know that when I pass a contract as an address parameter, I mean an address. Solidity actually is smart enough in this regard too!

Is there a PR you could make to clarify this? And great work! Glad you asked to learn even _more_

**Comment by blockdjango** [comment]
Oh man I don't know how to do a PR. I'll have to look into that thanks! I will when I figure it out.

**Comment by PatrickAlphaC** [comment]
Ah sorry, I mean a pull request 😅

PR = "Pull Request"

**Comment by PatrickAlphaC** [comment]
Closing due to stale
