### ISSUE TITLE
ValueError : Arguments must be given as key=value

### ISSUE THREAD

**Issue by xvc888** [PatrickAlphaC/smartcontract-lottery#70]
Hi all, I am stuck yet again and can't seem to find why. Any help would be greatly appreciated...

See code from console below

Cheers

$ brownie networks add development mainnet-fork cmd=ganache-cli hos =http://127.0.0.1 fork=https://eth-mainnet.alchemyapi.io/v2/MM65A1QtLDZXJUMxFXn_bIR5HyoKK4VX account=10 mnemonic=brownie port=8545                                                         
Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
Brownie v1.16.4 - Python development framework for Ethereum

  File "C:\Users\xav\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\_cli\__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "C:\Users\xav\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\_cli\networks.py", line 68, in main
    fn(*args["<arguments>"])
  File "C:\Users\xav\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\_cli\networks.py", line 111, in _add
    args = _parse_args(args)
  File "C:\Users\xav\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\_cli\networks.py", line 277, in _parse_args
    raise ValueError("Arguments must be given as key=value") from None
ValueError: Arguments must be given as key=value

Code from

**Comment by xvc888** [comment]
And my contract + yaml file:

Thank you in advance

// SPDX-License-Identifier: MIT
pragma solidity ^0.6.6;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";

contract Lottery {
    address payable[] public players;
    uint256 public usdEntryFee;
    AggregatorV3Interface internal ethUsdPriceFeed;

    constructor(address _priceFeedAddress) public {
        usdEntryFee = 50 * (10**18);
        ethUsdPriceFeed = AggregatorV3Interface(_priceFeedAddress);
    }

    function enter() public payable {
        // $50 minimum
        players.push(msg.sender);
    }

    function getEntranceFee() public view returns (uint256) {
        (, int256 price, , , , ) = ethUsdPriceFeed.latestRoundData;
        uint256 adjustedPrice = uint256(price) * 10**10; //18 decimals
        // $50, 2,000$ / ETH
        // 50/2,000
        // 50 * 100000 / 2000
        uint256 costToEnter = (usdEntryFee * 10**18) / price;
        return costToEnter;
    }

    function startLottery() public {}

    function endLottery() public {}
}
***************************************
Yaml file

dependencies:
- smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
networks:
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'

**Comment by PatrickAlphaC** [comment]
Could you make this on the full repo? THanks!

https://github.com/smartcontractkit/full-blockchain-solidity-course-py

**Comment by xvc888** [comment]
https://github.com/xvc888/Lottery-smart-contract-issue

**Comment by xvc888** [comment]
> Could you make this on the full repo? THanks!
> 
> https://github.com/smartcontractkit/full-blockchain-solidity-course-py

Done!
