### ISSUE TITLE
"Source \"@openzeppelin/contracts/access/Ownable.sol\" not found: File import callback not supported"

### ISSUE THREAD

**Issue by joebb10** [PatrickAlphaC/smartcontract-lottery#72]
```Lottery.sol

// SPDX-License-Identifier: MIT
pragma solidity ^0.6.6;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@openzeppelin/contracts/access/Ownable.sol";



```brownie-config.yaml

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'

// Open Zeppeling isn't working. have someone gotten the same error? What did u do? I've tried everything and still nothing.

**Comment by PatrickAlphaC** [comment]
Is this a compile error? or just VSCode linter telling you that?

Closing for now, feel free to follow up with the command you ran to get that error.

**Comment by joebb10** [comment]
Yes, this is a compile error. I ran "brownie compile" on the terminal. Even the openzeppelin forum doesn't know what is happening with this code. I've also tried to copy and paste the code from this repository and it didn't work.

**Comment by PatrickAlphaC** [comment]
Can you do a step by step of every command you ran to get this error starting with `git clone`?

**Comment by PatrickAlphaC** [comment]
Ahh ok. No I was asking you to walk step by step to getting your error starting with cloning this repo. Sounds like you don't get the issue when you clone the repo and run brownie compile?

**Comment by joebb10** [comment]
Yes, correct. The problem I'm seeing now is that if I clone the repo I get the complete code and I haven't finished the lottery part of the course. I've done the beginning only, that's why I'm still trying to use my code.

Also Patrick, just an idea: If possible make some videos you teaching how to create a dex, cex, etc. I've tried to create it by myself for starting a crypto payment startup, but I couldn't because I haven't found good contents teaching about it.

**Comment by PatrickAlphaC** [comment]
> I've done the beginning only, that's why I'm still trying to use my code.

Ah ok, so you'd need to find out where your differs.

And on that suggestion, thanks! We'll see if I get time to do that ahah.

**Comment by joebb10** [comment]
Thanks either, Patrick! I wish all the best to you. You are the best!
