### ISSUE TITLE
@pytest.fixture() functions are not accessed in other test files

### ISSUE THREAD

**Issue by HassanSayyed** [PatrickAlphaC/smartcontract-lottery#76]
both `check_local_blockchain_envs` and `lottery_contract` 
are not accessed in the both test files! 

> (parameter) check_local_blockchain_envs: Any
"check_local_blockchain_envs" is not accessed

**Comment by PatrickAlphaC** [comment]
Yeah, a lot of people having issues here.

I just reverted, could you do a new git pull and try again? 

https://github.com/PatrickAlphaC/smartcontract-lottery/commit/e3cd8e3b52311c27a557147c494d5bd1d9d3e753

**Comment by HassanSayyed** [comment]
Great ! the @pytest.fixture() function `lottery_contract` is accessed now

but causing error when running the tests [lottert_contract() testing error](https://github.com/PatrickAlphaC/smartcontract-lottery/commit/e3cd8e3b52311c27a557147c494d5bd1d9d3e753#commitcomment-77355545)
