### ISSUE TITLE
ValueError: Gas estimation failed: 'execution reverted'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

### ISSUE THREAD

**Issue by PrathamGit-dev** [PatrickAlphaC/smartcontract-lottery#77]
![image](https://user-images.githubusercontent.com/96198632/175807801-b7c32796-9c84-447e-9744-625388e75062.png)
 after the print statement of lottery balance, the next transaction of ending the lottery is not completing and showing the following error.

![image](https://user-images.githubusercontent.com/96198632/175807856-ee23335f-2a17-435c-b09f-15cc3719f0e3.png)

**Comment by PatrickAlphaC** [comment]
Interesting... do your tests pass? Could you try to re pull the repo from scratch?

**Comment by PrathamGit-dev** [comment]
Wrongly put wrong keyhash and fee(VRF2 instead of VRF1) in config, and hence transaction was reverting(). Now working fine. Thanks for replying.
