### ISSUE TITLE
Please Help AttributeError: Final argument must be a dict of transaction parameters that includes a `from` field specifying the address to deploy from

### ISSUE THREAD

**Issue by Deamonk1** [PatrickAlphaC/smartcontract-lottery#79]
Hi Patric , i get this error when i try run  brownie run scripts/delpoy_lottery.py scripts --- network rinkeby any idea on how to solve this issue Thanks here's the Error :   
Running 'scripts/deploy_lottery.py::main'...
  File "brownie/_cli/run.py", line 51, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 110, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/deploy_lottery.py", line 58, in main
    deploy_lottery()
  File "./scripts/deploy_lottery.py", line 14, in deploy_lottery
    lottery = Lottery.deploy(
  File "brownie/network/contract.py", line 544, in __call__
    raise AttributeError(
AttributeError: Final argument must be a dict of transaction parameters that includes a `from` field specifying the address to deploy from

<img width="1437" alt="Screen Shot 2022-07-07 at 9 52 08 PM" src="https://user-images.githubusercontent.com/100136975/177935325-48d60c1a-2b99-4bb8-9cb5-ed13a78a392d.png">

**Comment by PatrickAlphaC** [comment]
You're probably missing a comma or something somewhere. That error just means you need the `{"from": account}` and you have that.
