### ISSUE TITLE
TypeError: constructor requires no arguments

### ISSUE THREAD

**Issue by My922** [PatrickAlphaC/smartcontract-lottery#80]
I'm trying to do the test for test_get_entrance_fee, but the test always show:
TypeError: constructor requires no arguments

I don't know what's going on. 

Here's my test code:
<img width="871" alt="Screen Shot 2022-07-29 at 5 44 31 PM" src="https://user-images.githubusercontent.com/90160774/181863598-7f486c1f-e1f6-458e-b433-36c59e6911e0.png">

Here's my sol file:
<img width="879" alt="Screen Shot 2022-07-29 at 5 45 30 PM" src="https://user-images.githubusercontent.com/90160774/181863629-44aaf2eb-fdd6-4706-9685-2ee47b26ca59.png">
<img width="909" alt="Screen Shot 2022-07-29 at 5 46 49 PM" src="https://user-images.githubusercontent.com/90160774/181863680-4011db2a-1b23-4790-8656-2f25f6804d49.png">

And this is the error:
<img width="990" alt="Screen Shot 2022-07-29 at 5 46 21 PM" src="https://user-images.githubusercontent.com/90160774/181863662-3add406e-e59a-4c13-bcf5-500e1cd418d4.png">

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

It looks like your lottery doesn't take constructor arguments (see your `constructor` function in lottery.sol`) and your passing it args (see your line with `Lottery.deploy()`). Remove those args.

**Comment by My922** [comment]
Thank you! problem solved.
