### ISSUE TITLE
How can multiple people take part in a lottery?

### ISSUE THREAD

**Issue by abhishekchaturvedi10** [PatrickAlphaC/smartcontract-lottery#9]

**Comment by PatrickAlphaC** [comment]
Closing this as it’s a discussion more than an issue. Basically as is, many people can enter the pottery when it’s started.

**Comment by abhishekchaturvedi10** [comment]
When I try to enter the lottery from my other account on rinkeby then the players array does not get updated which means the new player has not been added or am Imissing something.
